### PR TITLE
Improve error handling

### PR DESCRIPTION
**Pull request by pabs3**
This depends on the params branch being merged.

I'm not sure if the approach is correct or not as
it doesn't seem to add anything very useful, since:

Errors from magic_setflags are very rare and will
not be triggered by the current codebases.

Errors from magic_setparam only happen when not yet
valid values are in max_future_compat and I'm not sure
if folks will care which values are valid or not.

### CODE REVIEW

**Comment by autarch** [comment]
Merged from the CLI. Thanks!

**Comment by pabs3** [comment]
FTR, I now think that croaking in response to future limit tags might
be the wrong approach. I think code using them would instead want to be
able to set a bunch of parameters and know which of them failed. The
code could then ignore some of the failures or croak on others.

-- 
bye,
pabs

https://wiki.debian.org/PaulWise

**Comment by autarch** [comment]
That API was inconsistent with every other piece of error handling in the library, which just croaks. I think a better way to do this would be to find a way to dynamically provide the acceptable parameter constant values as a class method. But I don't know of a way to do that short of parsing them `magic.h` file, which doesn't seem like a good idea for runtime code.

**Comment by pabs3** [comment]
OK, that makes sense. I like your class method idea and looking at the
libmagic code there is a simple way to achieve it, when initialising
the class, call magic_getparam with every tag value starting at one
more than maximum tag value File::LibMagic currently knows about and
when -1 is returned then stop and everything below that tag is valid. I
expect the #define MAGIC_PARAM_*_MAX values are going to be consecutive
integers so this should work unless that assumption gets violated.

#define MAGIC_PARAM_INDIR_MAX           0
#define MAGIC_PARAM_NAME_MAX            1
#define MAGIC_PARAM_ELF_PHNUM_MAX       2
#define MAGIC_PARAM_ELF_SHNUM_MAX       3
#define MAGIC_PARAM_ELF_NOTES_MAX       4
#define MAGIC_PARAM_REGEX_MAX           5
#define MAGIC_PARAM_BYTES_MAX           6

public int
magic_getparam(struct magic_set *ms, int param, void *val)
{
        if (ms == NULL)
                return -1;
        switch (param) {
        ...
        default:
                errno = EINVAL;
                return -1;
        }
}

-- 
bye,
pabs

https://wiki.debian.org/PaulWise

**Comment by autarch** [comment]
Yes, that's a great idea. A PR will be welcome if you have time but otherwise I will try to work on this when I have a chance.

**Pull request closed without merging**
